use super::DevShellConfig;

/// Generate a complete flake.nix string from devShell configs.
/// If `with_process_compose` is true, adds process-compose to buildInputs.
pub fn generate_flake(shells: &[DevShellConfig], with_process_compose: bool) -> String {
    let mut out = String::new();

    out.push_str(
        r#"{
  description = "Development environment generated by docker2nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
"#,
    );

    if shells.len() == 1 {
        out.push_str("        devShells.default = ");
        write_mkshell(&mut out, &shells[0], with_process_compose, 8);
        out.push_str(";\n");
    } else {
        out.push_str("        devShells = {\n");
        for (i, shell) in shells.iter().enumerate() {
            let name = if i == 0 { "default" } else { &shell.name };
            out.push_str(&format!("          {name} = "));
            write_mkshell(&mut out, shell, with_process_compose && i == 0, 10);
            out.push_str(";\n");
        }
        out.push_str("        };\n");
    }

    out.push_str(
        r#"      }
    );
}
"#,
    );

    out
}

fn write_mkshell(
    out: &mut String,
    shell: &DevShellConfig,
    with_process_compose: bool,
    indent: usize,
) {
    let pad = " ".repeat(indent);
    let pad2 = " ".repeat(indent + 2);

    out.push_str("pkgs.mkShell {\n");

    // buildInputs
    out.push_str(&format!("{pad2}buildInputs = with pkgs; [\n"));
    for pkg in &shell.build_inputs {
        out.push_str(&format!("{pad2}  {pkg}\n"));
    }
    if with_process_compose {
        out.push_str(&format!("{pad2}  process-compose\n"));
    }
    out.push_str(&format!("{pad2}];\n"));

    // env vars
    for (key, val) in &shell.env_vars {
        let escaped = val.replace('\"', "\\\"");
        out.push_str(&format!("{pad2}{key} = \"{escaped}\";\n"));
    }

    // shellHook
    if !shell.shell_hook_lines.is_empty() || with_process_compose {
        out.push_str(&format!("{pad2}shellHook = ''\n"));
        for line in &shell.shell_hook_lines {
            out.push_str(&format!("{pad2}  {line}\n"));
        }
        if with_process_compose {
            out.push_str(&format!(
                "{pad2}  echo \"Run 'process-compose up' to start services\"\n"
            ));
        }
        out.push_str(&format!("{pad2}'';\n"));
    }

    out.push_str(&format!("{pad}}}"));
}

#[cfg(test)]
mod tests {
    use super::*;
    use indexmap::IndexMap;

    #[test]
    fn test_generate_single_shell() {
        let shell = DevShellConfig {
            name: "default".into(),
            build_inputs: vec!["nodejs".into(), "curl".into()],
            env_vars: IndexMap::from([("FOO".into(), "bar".into())]),
            shell_hook_lines: vec![],
        };
        let output = generate_flake(&[shell], false);
        assert!(output.contains("nodejs"));
        assert!(output.contains("curl"));
        assert!(output.contains("FOO = \"bar\""));
        assert!(output.contains("devShells.default"));
    }

    #[test]
    fn test_generate_multiple_shells() {
        let s1 = DevShellConfig::new("default");
        let s2 = DevShellConfig::new("postgres");
        let output = generate_flake(&[s1, s2], false);
        assert!(output.contains("devShells = {"));
        assert!(output.contains("default ="));
        assert!(output.contains("postgres ="));
    }

    #[test]
    fn test_with_process_compose() {
        let shell = DevShellConfig::new("default");
        let output = generate_flake(&[shell], true);
        assert!(output.contains("process-compose"));
    }
}
